### PR TITLE
Fix Windows static build

### PR DESCRIPTION
**Pull request by Xiaobin0860**

### CODE REVIEW

**Comment by Xiaobin0860** [comment]
Already signed the Oracle Contribution Agreement (OCA)

**Comment by mwl4** [comment]
This MR should be merged, as still master does not build on MSVC with following cmake options:
```
-DBUILD_STATIC=true -DSTATIC_MSVCRT=true
```

Author of MR has responded that OCA has been signed. What is problem with merging it then?

**Comment by rsomla1** [comment]
Hi,

The problem is that our system thought the OCA is not signed and closed the request. I am trying to find out what has happened.

**Comment by mysql-admin** [comment]
Hi @Xiaobin086,
We can't find an  OCA from you in our system. Possibly your OCA is not linked correctly to your name, or github handle.
Please email lenka.kasparova@oracle.com with details

Thanks for contributing to MySQL
==Omer

**Pull request closed without merging**
