### PR TITLE
Fix copypaste errors

### PR DESCRIPTION
**Pull request by kstreitova**
Fix some (probably) copypaste errors in libmysql_dynamic_proxy.cpp
that cause the build to fail

### CODE REVIEW

**Comment by kstreitova** [comment]
It seems that SUSE is already listed in the list of signatories as "SUSE Linux Products GmbH - OpenJDK".

Is this sufficient?

**Comment by kstreitova** [comment]
This PR was closed before answering my question regarding OCA. Can anybody check it, please? Thanks!

**Comment by mysql-admin** [comment]
Reopening per above request. Please sign an OCA as indicated above

Thanks
==Omer

**Comment by kstreitova** [comment]
Thanks for reopening, Omer. SUSE is already listed in the list of OCA signatories as "SUSE Linux Products GmbH - OpenJDK". Can you please confirm if this is sufficient or if I have to sign it again? Thank you!

**Comment by ericcurtin** [comment]
Hi @kstreitova,

The git logs tell you all you need to know. These are the only current contributors:

Bogdan Degtyariov <bogdan.degtyariov@oracle.com>
Jakub Nowakowski <jakub.nowakowski@oracle.com>
Kent Boortz <kent.boortz@oracle.com>
Luís Silva <luis.m.silva@oracle.com>
Rafal Somla <rafal.somla@oracle.com

They are unlikely to accept your contribution regardless, the OCA appears to be just "red tape" to further help prevent non-oracle people from being helpful and contributing enhancements and fixes. This project is only open source in that you can view and fork the code.

Just remember that the GPL is really strict and if you link your code against GPL work and distribute your binaries, you should release the code! Maybe forking this isn't worth it as your code will likely never be merged upstream, so it will become a disaster to maintain.

I'v forked v1.1 of this, it builds against MariaDB 10.0:

https://github.com/ericcurtin/mariadb-connector-cpp

I'm also in the process of creating my own C++ interface for my specific use case (it's far for ready, give it a week or two):

https://github.com/ericcurtin/mariadbcpp

Also, gonna change that license to LGPL so people can dynamically link distributed binaries without releasing the source code.

Feel free to reach out to MariaDB community too! They are more than welcome to external contributors.

**Comment by ericcurtin** [comment]
@kstreitova 

I'd gladly merge your fix here:

https://github.com/ericcurtin/mariadb-connector-cpp

Please open the PR :)

**Comment by mysql-admin** [comment]
Reopening as OCA handling is still pending response

**Pull request closed without merging**
